### ISSUE TITLE
压缩后比压缩之前还要大了

### ISSUE THREAD

**Issue by hurriedlu** [zanjie1999/mecopy#1]
emmm发现了一个小问题，压缩后比压缩之前还要大了
![image](https://github.com/zanjie1999/mecopy/assets/84308195/bfa64d38-81dc-4a26-8a78-bf4f7a89777f)

之所以想这么试一下是因为用玩客云搭建了一个minio作为图床，因为板载的emmc存储有限（总共才8G！！！！），为了能尽可能的多存储一些图片想试试先压缩再上传，没想到发现压缩完反而更大了233333

**Comment by zanjie1999** [comment]
乐了，我暂时没有遇到这种情况，但是我可以改一下，如果压缩的图片比压缩前的更大，那就使用原图片，或是自定义压缩比

**Comment by zanjie1999** [comment]
好了，用3.0
